// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK-7wpLrSqZPs_v4tmv2OvoK7AyYoJCFE',
    appId: '1:563095787211:web:989420db2ae11e66116d4e',
    messagingSenderId: '563095787211',
    projectId: 'cargoapp-70904',
    authDomain: 'cargoapp-70904.firebaseapp.com',
    storageBucket: 'cargoapp-70904.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFwWs1nGAwR-wO6wCLEK8VJzr15qyXyPo',
    appId: '1:563095787211:android:13a419a1144a2f98116d4e',
    messagingSenderId: '563095787211',
    projectId: 'cargoapp-70904',
    storageBucket: 'cargoapp-70904.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLVGfSyMo7CdAD5zbLGPY8WixWlbII5Xk',
    appId: '1:563095787211:ios:83dfa5fe1ecad51d116d4e',
    messagingSenderId: '563095787211',
    projectId: 'cargoapp-70904',
    storageBucket: 'cargoapp-70904.firebasestorage.app',
    androidClientId: '563095787211-lnr8ekblknm6u0eoq9k6tlvdsprihh9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.cargoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLVGfSyMo7CdAD5zbLGPY8WixWlbII5Xk',
    appId: '1:563095787211:ios:83dfa5fe1ecad51d116d4e',
    messagingSenderId: '563095787211',
    projectId: 'cargoapp-70904',
    storageBucket: 'cargoapp-70904.firebasestorage.app',
    androidClientId: '563095787211-lnr8ekblknm6u0eoq9k6tlvdsprihh9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.cargoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK-7wpLrSqZPs_v4tmv2OvoK7AyYoJCFE',
    appId: '1:563095787211:web:d3e37f93f75f4fae116d4e',
    messagingSenderId: '563095787211',
    projectId: 'cargoapp-70904',
    authDomain: 'cargoapp-70904.firebaseapp.com',
    storageBucket: 'cargoapp-70904.firebasestorage.app',
  );

}